---
- name: git clone gitolite-admin
  tags: gitolite
  sudo: yes
  sudo_user: "{{ gitolite_user_name }}"
  git:
    force=yes
    accept_hostkey=yes
    repo={{ gitolite_user_name }}@localhost:gitolite-admin.git
    remote=origin
    dest={{ gitolite_user_home }}/gitolite-admin

# Install a gitolite repositories configuration file "gitolite.conf"
- name: Install gitolite.conf
  tags: gitolite
  register: gitolite_install_gitolite_conf
  template:
    src=gitolite.conf.j2
    dest={{ gitolite_user_home }}/gitolite-admin/conf/gitolite.conf
    mode=0640
    owner={{ gitolite_user_name }}
    group={{ gitolite_user_group }}

# Install gitolite user accounts for git+ssh
- name: Install gitolite SSH user accounts
  tags: gitolite
  register: gitolite_install_gitolite_ssh_user_accounts
  with_items: gitolite_accounts_ssh
  copy:
    src=files/gitolite/users/ssh/{{ item }}.pub
    dest={{ gitolite_user_home }}/gitolite-admin/keydir/{{ item }}.pub
    mode=0640
    owner={{ gitolite_user_name }}
    group={{ gitolite_user_group }}


# Manage changes inside the gitolite-admin repository
#   stage changes
- name: git add gitolite-admin
  tags: gitolite
  when: gitolite_install_gitolite_conf.changed or gitolite_install_gitolite_ssh_user_accounts.changed
  register: gitolite_git_add_gitolite_admin
  sudo: yes
  sudo_user: "{{ gitolite_user_name }}"
  command: git add --all
    chdir={{ gitolite_user_home }}/gitolite-admin

#   commit changes
- name: git commit gitolite-admin
  tags: gitolite
  when: gitolite_git_add_gitolite_admin.changed
  register: gitolite_git_commit_gitolite_admin
  sudo: yes
  sudo_user: "{{ gitolite_user_name }}"
  command: git commit -m 'Updated gitolite-admin by Ansible'
    chdir={{ gitolite_user_home }}/gitolite-admin

#   push changes
- name: git push gitolite-admin
  tags: gitolite
  when: gitolite_git_commit_gitolite_admin.changed
  sudo: yes
  sudo_user: "{{ gitolite_user_name }}"
  command: git push --set-upstream origin master
    chdir={{ gitolite_user_home }}/gitolite-admin
